import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { ReactQueryProvider } from './ReactQueryProvider'
import LeftSideBar from '@/layouts/LeftSideBar/LeftSideBar'
import RightSideBar from '@/layouts/RightSideBar.tsx/RightSideBar'
import Header from '@/layouts/Header/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
   title: 'Home page',
   description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <ReactQueryProvider>
         <html lang='en'>
            <body className={inter.className}>
               <div className='flex'>
                  <LeftSideBar />
                  <div className='flex-1'>
                     <Header />
                     {children}
                  </div>
                  <RightSideBar />
               </div>
               <ToastContainer autoClose={2000} />
            </body>
         </html>
      </ReactQueryProvider>
   )
}
